[package]
name = "subnetcalculator"
authors = ["Fabian Holler, @Tanzkalmar35"]
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.24.1"
eframe = { version = "0.24.1", features = ["default_fonts"] }
env_logger = "0.10.1"
cc = "1.0.83"
